Created by: Damien Stephens <br>
Created on: August 26, 2020

This file shows a simple example of binary data classification using an artificial neural network (ANN).

# Imports

In [40]:
import tensorflow as tf
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix, accuracy_score

# Data Preprocessing and Exploration

In [2]:
# import the dataset from Churn_Modelling.csv
data_path = 'Churn_Modelling.csv'
dataset = pd.read_csv(data_path)

In [3]:
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [4]:
# select the independent variable
# use drop() to select the matrix of features (the independent variables) by dropping columns that are not
# correlated with the output
# axis=0 selects the indexes, axis=1 selects the columns
x = dataset.drop(labels=['RowNumber', 'CustomerId', 'Surname', 'Exited'], axis=1)

# select the dependent variable
y = dataset['Exited']

In [5]:
# Geography has 3 categories and Gender has 2 categories
# we will convert this categorical data into numerical data below
x.head(10)

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619    France  Female   42       2       0.00              1   
1          608     Spain  Female   41       1   83807.86              1   
2          502    France  Female   42       8  159660.80              3   
3          699    France  Female   39       1       0.00              2   
4          850     Spain  Female   43       2  125510.82              1   
5          645     Spain    Male   44       8  113755.78              2   
6          822    France    Male   50       7       0.00              2   
7          376   Germany  Female   29       4  115046.74              4   
8          501    France    Male   44       4  142051.07              2   
9          684    France    Male   27       2  134603.88              1   

   HasCrCard  IsActiveMember  EstimatedSalary  
0          1               1        101348.88  
1          0               1        112542.58  
2          1               0        113931.57  
3          0               0         93826.63  
4          1               1         79084.10  
5          1               0        149756.71  
6          1               1         10062.80  
7          1               0        119346.88  
8          0               1         74940.50  
9          1               1         71725.73

In [6]:
y.head()

0    1
1    0
2    1
3    0
4    0
Name: Exited, dtype: int64

In [7]:
# encode the Geography categorical data
# fit the data into the object label_1, then transform the data
label_1 = LabelEncoder()
x['Geography'] = label_1.fit_transform(x['Geography'])

In [8]:
# now the Geography column has been converted into numerical data
x.head(10)

CreditScore  Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619          0  Female   42       2       0.00              1   
1          608          2  Female   41       1   83807.86              1   
2          502          0  Female   42       8  159660.80              3   
3          699          0  Female   39       1       0.00              2   
4          850          2  Female   43       2  125510.82              1   
5          645          2    Male   44       8  113755.78              2   
6          822          0    Male   50       7       0.00              2   
7          376          1  Female   29       4  115046.74              4   
8          501          0    Male   44       4  142051.07              2   
9          684          0    Male   27       2  134603.88              1   

   HasCrCard  IsActiveMember  EstimatedSalary  
0          1               1        101348.88  
1          0               1        112542.58  
2          1               0        113931.57  
3          0               0         93826.63  
4          1               1         79084.10  
5          1               0        149756.71  
6          1               1         10062.80  
7          1               0        119346.88  
8          0               1         74940.50  
9          1               1         71725.73

In [9]:
# encode the Gender categorical data
label_2 = LabelEncoder()
x['Gender'] = label_2.fit_transform(x['Gender'])

In [10]:
# now the Gender column has been converted into numerical data
x.head(10)

CreditScore  Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619          0       0   42       2       0.00              1   
1          608          2       0   41       1   83807.86              1   
2          502          0       0   42       8  159660.80              3   
3          699          0       0   39       1       0.00              2   
4          850          2       0   43       2  125510.82              1   
5          645          2       1   44       8  113755.78              2   
6          822          0       1   50       7       0.00              2   
7          376          1       0   29       4  115046.74              4   
8          501          0       1   44       4  142051.07              2   
9          684          0       1   27       2  134603.88              1   

   HasCrCard  IsActiveMember  EstimatedSalary  
0          1               1        101348.88  
1          0               1        112542.58  
2          1               0        113931.57  
3          0               0         93826.63  
4          1               1         79084.10  
5          1               0        149756.71  
6          1               1         10062.80  
7          1               0        119346.88  
8          0               1         74940.50  
9          1               1         71725.73

In [11]:
# avoid the "dummy variable trap"
# this splits the Geography column into two columns where the original geography has been changed to 
# binary (00, 01, 10, 11) so the model does not interpret one geographic location higher than another
x = pd.get_dummies(data=x, drop_first=True, columns=['Geography'])

In [12]:
x.head(10)

CreditScore  Gender  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0          619       0   42       2       0.00              1          1   
1          608       0   41       1   83807.86              1          0   
2          502       0   42       8  159660.80              3          1   
3          699       0   39       1       0.00              2          0   
4          850       0   43       2  125510.82              1          1   
5          645       1   44       8  113755.78              2          1   
6          822       1   50       7       0.00              2          1   
7          376       0   29       4  115046.74              4          1   
8          501       1   44       4  142051.07              2          0   
9          684       1   27       2  134603.88              1          1   

   IsActiveMember  EstimatedSalary  Geography_1  Geography_2  
0               1        101348.88            0            0  
1               1        112542.58            0            1  
2               0        113931.57            0            0  
3               0         93826.63            0            0  
4               1         79084.10            0            1  
5               0        149756.71            0            1  
6               1         10062.80            0            0  
7               0        119346.88            1            0  
8               1         74940.50            0            0  
9               1         71725.73            0            0

In [13]:
# split the dataset into train and test datasets
# test size = 20% of the dataset, so training size is 80% of the dataset
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)

In [14]:
# feature scaling
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [15]:
x_train

array([[ 0.16958176, -1.09168714, -0.46460796, ...,  1.10643166,
        -0.5698444 ,  1.74309049],
       [-2.30455945,  0.91601335,  0.30102557, ..., -0.74866447,
         1.75486502, -0.57369368],
       [-1.19119591, -1.09168714, -0.94312892, ...,  1.48533467,
        -0.5698444 , -0.57369368],
       ...,
       [ 0.9015152 ,  0.91601335, -0.36890377, ...,  1.41231994,
        -0.5698444 , -0.57369368],
       [-0.62420521, -1.09168714, -0.08179119, ...,  0.84432121,
        -0.5698444 ,  1.74309049],
       [-0.28401079, -1.09168714,  0.87525072, ...,  0.32472465,
         1.75486502, -0.57369368]])

In [16]:
x_test

array([[-0.55204276, -1.09168714, -0.36890377, ...,  1.61085707,
         1.75486502, -0.57369368],
       [-1.31490297, -1.09168714,  0.10961719, ...,  0.49587037,
        -0.5698444 , -0.57369368],
       [ 0.57162971, -1.09168714,  0.30102557, ..., -0.42478674,
        -0.5698444 ,  1.74309049],
       ...,
       [-0.74791227,  0.91601335, -0.27319958, ...,  0.71888467,
        -0.5698444 ,  1.74309049],
       [-0.00566991,  0.91601335, -0.46460796, ..., -1.54507805,
         1.75486502, -0.57369368],
       [-0.79945688,  0.91601335, -0.84742473, ...,  1.61255917,
         1.75486502, -0.57369368]])

# Build the Model

In [17]:
# create an object (initializing the ANN)
model = tf.keras.models.Sequential()

In [18]:
# check the input_dimensions
x.shape

(10000, 11)

In [19]:
# add the input layer
# units=6     trick: take average of input=11 and output=1, hence (11+1)/2=6
# input dimension=11
model.add(tf.keras.layers.Dense(units=6, activation='relu', input_dim=11))

In [20]:
# add the hidden layer
model.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [21]:
# add the output layer
# since we have binary outputs, use sigmoid instead of softmax
model.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

In [22]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 6)                 72        
_________________________________________________________________
dense_1 (Dense)              (None, 6)                 42        
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 7         
Total params: 121
Trainable params: 121
Non-trainable params: 0
_________________________________________________________________


In [23]:
# compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Train the Model

In [24]:
# train the ANN model
model.fit(x_train, y_train.to_numpy(), batch_size=10, epochs=20)

Epoch 1/20
800/800 [==============================] - 0s 420us/step - loss: 0.5277 - accuracy: 0.7880
Epoch 2/20
800/800 [==============================] - 0s 416us/step - loss: 0.4431 - accuracy: 0.80200s - loss: 0.4501 - accuracy: 
Epoch 3/20
800/800 [==============================] - 0s 406us/step - loss: 0.4172 - accuracy: 0.8142
Epoch 4/20
800/800 [==============================] - 0s 413us/step - loss: 0.4005 - accuracy: 0.8282
Epoch 5/20
800/800 [==============================] - 0s 401us/step - loss: 0.3838 - accuracy: 0.8409
Epoch 6/20
800/800 [==============================] - 0s 413us/step - loss: 0.3697 - accuracy: 0.8485
Epoch 7/20
800/800 [==============================] - 0s 408us/step - loss: 0.3603 - accuracy: 0.8531
Epoch 8/20
800/800 [==============================] - 0s 402us/step - loss: 0.3542 - accuracy: 0.8561
Epoch 9/20
800/800 [==============================] - 0s 416us/step - loss: 0.3497 - accuracy: 0.8601
Epoch 10/20
800/800 [==============================]

# Model Evaluation and Prediction

In [25]:
# evaluate the model
test_loss, test_accuracy = model.evaluate(x_test, y_test.to_numpy())

63/63 [==============================] - 0s 390us/step - loss: 0.3340 - accuracy: 0.8635


In [26]:
print(f"Test Accuracy: {test_accuracy*100:.2f}%")

Test Accuracy: 86.35%


In [27]:
# make predictions
y_pred = model.predict_classes(x_test)

Instructions for updating:
Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).


In [28]:
# look at the predicted values
print(y_pred)

[[0]
 [0]
 [0]
 ...
 [0]
 [0]
 [0]]


In [29]:
# look at the actual values
print(y_test)

9394    0
898     1
2398    0
5906    0
2343    0
       ..
1037    0
2899    0
9549    0
2740    0
6690    0
Name: Exited, Length: 2000, dtype: int64


In [ ]:
# convert the vector to an array
y_test = y_test.to_numpy()

In [38]:
# make individual predictions based on index location
index = 0
print(f"y_pred[{index}]: {y_pred[index]}") 
print(f"y_test[{index}]: {y_test[index]}")

y_pred[0]: [0]
y_test[0]: 0


In [44]:
# confusion matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1526   69]
 [ 204  201]]


In [46]:
# calculate accuracy based on confusion matrix
acc_cm = accuracy_score(y_test, y_pred)
print(f"Accuracy of Confusion Matrix: {acc_cm*100:.2f}%")

Accuracy of Confusion Matrix: 86.35%
